'use client';

import { ComparisonSlider } from './ComparisonSlider';
import { roomEvidenceFrame } from '@/data/evidenceFrames';
import { interiorRenders } from '@/data/interiors';
import { houseModel } from '@/data/house';

export function BeforeConceptSection() {
  const rooms = houseModel.rooms.filter((r) => interiorRenders[r.id] && roomEvidenceFrame[r.id]);

  return (
    <section id="comparisons" className="mx-auto max-w-6xl px-6 py-20">
      <p className="text-xs font-semibold uppercase tracking-[0.3em] text-olive">Before / after</p>
      <h2 className="font-display mt-3 text-3xl text-charcoal">Drag to compare, room by room</h2>
      <p className="mt-4 max-w-2xl text-charcoal/70">
        Every &ldquo;after&rdquo; below was generated by Nano Banana from the matching construction frame on the left,
        which is used as a hard architectural reference — same camera, same walls, same window openings, same view out.
        The design is applied; the building is not invented. All {rooms.length} rooms are shown.
      </p>
      <div className="mt-10 grid grid-cols-1 gap-6 md:grid-cols-2">
        {rooms.map((room) => (
          <ComparisonSlider
            key={room.id}
            label={room.hotspotLabel}
            beforeSrc={roomEvidenceFrame[room.id].path}
            beforeAlt={`Unfinished ${room.hotspotLabel}`}
            afterSrc={interiorRenders[room.id]!.path}
            afterAlt={`Warm-modern-luxury interior concept for ${room.hotspotLabel}`}
          />
        ))}
      </div>
      <p className="mt-8 max-w-2xl text-xs text-charcoal/50">
        Concept visualization only. The MAMAD&rsquo;s blast door, blast window and filtration penetration are held fixed
        in every generation and must not be altered in construction.
      </p>
    </section>
  );
}
