import { afterEach, describe, expect, it, vi } from 'vitest';
import { roomEvidenceFrame } from '@/data/evidenceFrames';

/**
 * Route-level proof that a source image cannot be paired with a room it does
 * not belong to.
 *
 * The helper is unit-tested in ai-higgsfield-source.test.ts; this exercises
 * the real POST handler, because the defect being closed was precisely that
 * the route ran a check which a public path slipped past. A helper test alone
 * would not have caught that.
 */
describe('POST /api/nano-banana/generate — source/room binding', () => {
  const ORIGINAL_ENV = { ...process.env };

  afterEach(() => {
    process.env = { ...ORIGINAL_ENV };
    vi.resetModules();
  });

  async function post(body: unknown) {
    vi.resetModules();
    const { POST } = await import('@/app/api/nano-banana/generate/route');
    const request = new Request('http://localhost:3000/api/nano-banana/generate', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body),
    });
    // The route only reads standard Request members plus headers.
    const response = await POST(request as never);
    return { status: response.status, body: await response.json() };
  }

  const base = {
    styleVariant: 'warm-oak',
    idempotencyKey: `k-${Math.random().toString(36).slice(2, 12)}`,
  };

  it("rejects another room's evidence frame submitted under this room's id (regression)", async () => {
    // Without this the generated bytes come from the living room while the
    // stored, signed result is tagged MAMAD — a falsely room-tagged source
    // that later refinements and billed Higgsfield jobs would then trust.
    const { status, body } = await post({
      ...base,
      idempotencyKey: 'cross-room-attempt-1',
      roomId: 'mamad',
      sourceAssetPath: roomEvidenceFrame.living.path,
    });
    expect(status).toBe(400);
    expect(String(body.error)).toMatch(/different room/i);
  });

  it('rejects an arbitrary public path that is no room\'s evidence frame', async () => {
    const { status } = await post({
      ...base,
      idempotencyKey: 'cross-room-attempt-2',
      roomId: 'mamad',
      sourceAssetPath: '/generated/concepts/living.svg',
    });
    expect(status).toBe(400);
  });

  it("accepts the room's own evidence frame — the studio's real first-generation path", async () => {
    const { status } = await post({
      ...base,
      idempotencyKey: 'own-frame-ok-1',
      roomId: 'mamad',
      sourceAssetPath: roomEvidenceFrame.mamad.path,
    });
    expect(status).toBe(200);
  });

  it('accepts a shared open-zone frame for each room that shares it', async () => {
    // living/kitchen/dining are one photographed space; the binding is
    // per-room, so this must not read as a mismatch.
    const { status } = await post({
      ...base,
      idempotencyKey: 'shared-frame-ok-1',
      roomId: 'kitchen',
      sourceAssetPath: roomEvidenceFrame.living.path,
    });
    expect(status).toBe(200);
  });

  it('still accepts a request with no source at all', async () => {
    const { status } = await post({ ...base, idempotencyKey: 'no-source-ok-1', roomId: 'mamad' });
    expect(status).toBe(200);
  });
});
