/**
 * Real walkthrough frames, one gallery per room.
 *
 * Extracted from Ali_House_Walkthrough_Claude_Under30MB.mp4 (61.4s handheld
 * portrait walk of the house during construction) at 10fps, then reduced to the
 * sharpest frame per 0.5s window by Laplacian variance x tiled edge energy.
 * Room assignment is derived from the architect floor plan cross-checked against
 * the walk order in the video - see analysis/house-evidence.json.
 *
 * GENERATED by scripts/publish-frames - do not hand-edit.
 */

import type { RoomId } from '@/lib/types';

export interface EvidenceShot {
  path: string;
  seconds: number;
  timestamp: string;
  sharpness: number;
}

export interface RoomEvidence {
  hero: number;
  confidence: 'high' | 'medium-high' | 'medium' | 'low';
  caption: string;
  shots: EvidenceShot[];
}

export const roomEvidence: Record<RoomId, RoomEvidence> = {
  terrace_nw: {
    hero: 22.6,
    confidence: 'medium-high',
    caption: "L-corner balcony, both parapet bays and the rendered corner pier in frame.",
    shots: [
      { path: '/evidence/frames/terrace_nw/00_t022.8.jpg', seconds: 22.8, timestamp: '00:22', sharpness: 1448 },
      { path: '/evidence/frames/terrace_nw/01_t021.3.jpg', seconds: 21.3, timestamp: '00:21', sharpness: 2592 },
      { path: '/evidence/frames/terrace_nw/02_t023.5.jpg', seconds: 23.5, timestamp: '00:23', sharpness: 668 },
      { path: '/evidence/frames/terrace_nw/03_t024.0.jpg', seconds: 24.0, timestamp: '00:24', sharpness: 91 },
    ],
  },
  stair_landing: {
    hero: 2.1,
    confidence: 'high',
    caption: "Travertine treads rising to the covered landing at the front door.",
    shots: [
      { path: '/evidence/frames/stair_landing/00_t002.1.jpg', seconds: 2.1, timestamp: '00:02', sharpness: 3902 },
      { path: '/evidence/frames/stair_landing/01_t003.0.jpg', seconds: 3.0, timestamp: '00:03', sharpness: 7657 },
      { path: '/evidence/frames/stair_landing/02_t004.7.jpg', seconds: 4.7, timestamp: '00:04', sharpness: 2520 },
      { path: '/evidence/frames/stair_landing/03_t005.6.jpg', seconds: 5.6, timestamp: '00:05', sharpness: 1703 },
      { path: '/evidence/frames/stair_landing/04_t007.0.jpg', seconds: 7.0, timestamp: '00:07', sharpness: 784 },
    ],
  },
  living: {
    hero: 15.1,
    confidence: 'high',
    caption: "The three tall west windows in one plane, with the RC piers between the glazed bays.",
    shots: [
      { path: '/evidence/frames/living/00_t015.1.jpg', seconds: 15.1, timestamp: '00:15', sharpness: 4460 },
      { path: '/evidence/frames/living/01_t012.6.jpg', seconds: 12.6, timestamp: '00:12', sharpness: 9562 },
      { path: '/evidence/frames/living/02_t013.8.jpg', seconds: 13.8, timestamp: '00:13', sharpness: 9142 },
      { path: '/evidence/frames/living/03_t017.0.jpg', seconds: 17.0, timestamp: '00:17', sharpness: 3088 },
      { path: '/evidence/frames/living/04_t018.0.jpg', seconds: 18.0, timestamp: '00:18', sharpness: 4307 },
      { path: '/evidence/frames/living/05_t059.4.jpg', seconds: 59.4, timestamp: '00:59', sharpness: 8076 },
      { path: '/evidence/frames/living/06_t061.2.jpg', seconds: 61.2, timestamp: '01:01', sharpness: 31242 },
    ],
  },
  entry_hall: {
    hero: 9.1,
    confidence: 'medium-high',
    caption: "The threshold looking down the hall, brightening into the social zone.",
    shots: [
      { path: '/evidence/frames/entry_hall/00_t008.9.jpg', seconds: 8.9, timestamp: '00:08', sharpness: 1782 },
      { path: '/evidence/frames/entry_hall/01_t008.3.jpg', seconds: 8.3, timestamp: '00:08', sharpness: 1074 },
      { path: '/evidence/frames/entry_hall/02_t009.9.jpg', seconds: 9.9, timestamp: '00:09', sharpness: 3117 },
      { path: '/evidence/frames/entry_hall/03_t010.3.jpg', seconds: 10.3, timestamp: '00:10', sharpness: 3983 },
    ],
  },
  kitchen: {
    hero: 13.6,
    confidence: 'medium',
    caption: "The small recessed square window with no shutter box, past the projecting SW pier.",
    shots: [
      { path: '/evidence/frames/kitchen/00_t013.4.jpg', seconds: 13.4, timestamp: '00:13', sharpness: 6631 },
      { path: '/evidence/frames/kitchen/01_t014.2.jpg', seconds: 14.2, timestamp: '00:14', sharpness: 3967 },
      { path: '/evidence/frames/kitchen/02_t014.6.jpg', seconds: 14.6, timestamp: '00:14', sharpness: 3338 },
    ],
  },
  dining: {
    hero: 18.6,
    confidence: 'medium',
    caption: "South across the open strip to the glazed sliding panel \u2014 dining, kitchen and living read as one room.",
    shots: [
      { path: '/evidence/frames/dining/00_t018.9.jpg', seconds: 18.9, timestamp: '00:18', sharpness: 212 },
      { path: '/evidence/frames/dining/01_t019.4.jpg', seconds: 19.4, timestamp: '00:19', sharpness: 409 },
      { path: '/evidence/frames/dining/02_t020.0.jpg', seconds: 20.0, timestamp: '00:20', sharpness: 414 },
      { path: '/evidence/frames/dining/03_t020.8.jpg', seconds: 20.8, timestamp: '00:20', sharpness: 500 },
    ],
  },
  terrace_south: {
    hero: 20.8,
    confidence: 'low',
    caption: "Never entered in the walkthrough. Nearest evidence is the glazed south opening it sits behind.",
    shots: [
      { path: '/evidence/frames/terrace_south/00_t020.8.jpg', seconds: 20.8, timestamp: '00:20', sharpness: 500 },
    ],
  },
  mamad: {
    hero: 39.6,
    confidence: 'medium',
    caption: "The protected room: single already-glazed blast window in the north wall, round filtration sleeve beside it.",
    shots: [
      { path: '/evidence/frames/mamad/00_t039.9.jpg', seconds: 39.9, timestamp: '00:39', sharpness: 639 },
      { path: '/evidence/frames/mamad/01_t038.6.jpg', seconds: 38.6, timestamp: '00:38', sharpness: 1367 },
      { path: '/evidence/frames/mamad/02_t040.3.jpg', seconds: 40.3, timestamp: '00:40', sharpness: 6230 },
      { path: '/evidence/frames/mamad/03_t041.6.jpg', seconds: 41.6, timestamp: '00:41', sharpness: 2383 },
    ],
  },
  mamad_recess: {
    hero: 36.1,
    confidence: 'medium',
    caption: "Ceiling downstand and switch bank, metal MAMAD door frame straight ahead.",
    shots: [
      { path: '/evidence/frames/mamad_recess/00_t036.0.jpg', seconds: 36.0, timestamp: '00:36', sharpness: 652 },
      { path: '/evidence/frames/mamad_recess/01_t036.5.jpg', seconds: 36.5, timestamp: '00:36', sharpness: 241 },
      { path: '/evidence/frames/mamad_recess/02_t037.2.jpg', seconds: 37.2, timestamp: '00:37', sharpness: 737 },
      { path: '/evidence/frames/mamad_recess/03_t037.7.jpg', seconds: 37.7, timestamp: '00:37', sharpness: 810 },
    ],
  },
  corridor: {
    hero: 33.6,
    confidence: 'high',
    caption: "Windowless distribution band \u2014 two bare doorways plus the metal MAMAD frame.",
    shots: [
      { path: '/evidence/frames/corridor/00_t033.8.jpg', seconds: 33.8, timestamp: '00:33', sharpness: 485 },
      { path: '/evidence/frames/corridor/01_t025.8.jpg', seconds: 25.8, timestamp: '00:25', sharpness: 6275 },
      { path: '/evidence/frames/corridor/02_t026.9.jpg', seconds: 26.9, timestamp: '00:26', sharpness: 2927 },
      { path: '/evidence/frames/corridor/03_t034.2.jpg', seconds: 34.2, timestamp: '00:34', sharpness: 1424 },
      { path: '/evidence/frames/corridor/04_t050.4.jpg', seconds: 50.4, timestamp: '00:50', sharpness: 9 },
      { path: '/evidence/frames/corridor/05_t051.5.jpg', seconds: 51.5, timestamp: '00:51', sharpness: 13 },
    ],
  },
  bath_family: {
    hero: 30.6,
    confidence: 'high',
    caption: "Tanked wet room, high square window taking hard direct sun, bitumen to ~0.9 m.",
    shots: [
      { path: '/evidence/frames/bath_family/00_t030.6.jpg', seconds: 30.6, timestamp: '00:30', sharpness: 207 },
      { path: '/evidence/frames/bath_family/01_t028.5.jpg', seconds: 28.5, timestamp: '00:28', sharpness: 397 },
      { path: '/evidence/frames/bath_family/02_t029.8.jpg', seconds: 29.8, timestamp: '00:29', sharpness: 447 },
      { path: '/evidence/frames/bath_family/03_t031.3.jpg', seconds: 31.3, timestamp: '00:31', sharpness: 29 },
    ],
  },
  bath_ensuite: {
    hero: 48.3,
    confidence: 'medium-high',
    caption: "Entered through the parents' bedroom \u2014 bare block reveal, dark tanking.",
    shots: [
      { path: '/evidence/frames/bath_ensuite/00_t048.3.jpg', seconds: 48.3, timestamp: '00:48', sharpness: 557 },
      { path: '/evidence/frames/bath_ensuite/01_t047.3.jpg', seconds: 47.3, timestamp: '00:47', sharpness: 348 },
      { path: '/evidence/frames/bath_ensuite/02_t047.5.jpg', seconds: 47.5, timestamp: '00:47', sharpness: 241 },
      { path: '/evidence/frames/bath_ensuite/03_t049.3.jpg', seconds: 49.3, timestamp: '00:49', sharpness: 59 },
    ],
  },
  wc: {
    hero: 26.0,
    confidence: 'low',
    caption: "Never entered in the walkthrough. Shown here is the adjacent circulation, not the WC itself.",
    shots: [
      { path: '/evidence/frames/wc/00_t026.0.jpg', seconds: 26.0, timestamp: '00:26', sharpness: 6361 },
    ],
  },
  bedroom_twin: {
    hero: 55.1,
    confidence: 'medium-high',
    caption: "Two bare window openings on adjacent north and east walls, meeting at the corner.",
    shots: [
      { path: '/evidence/frames/bedroom_twin/00_t055.4.jpg', seconds: 55.4, timestamp: '00:55', sharpness: 1358 },
      { path: '/evidence/frames/bedroom_twin/01_t053.4.jpg', seconds: 53.4, timestamp: '00:53', sharpness: 882 },
      { path: '/evidence/frames/bedroom_twin/02_t054.7.jpg', seconds: 54.7, timestamp: '00:54', sharpness: 521 },
      { path: '/evidence/frames/bedroom_twin/03_t055.7.jpg', seconds: 55.7, timestamp: '00:55', sharpness: 546 },
      { path: '/evidence/frames/bedroom_twin/04_t057.0.jpg', seconds: 57.0, timestamp: '00:57', sharpness: 294 },
    ],
  },
  bedroom_parents: {
    hero: 45.1,
    confidence: 'medium-high',
    caption: "Corner room with east and south openings in frame, just before the camera turns into the en-suite.",
    shots: [
      { path: '/evidence/frames/bedroom_parents/00_t045.0.jpg', seconds: 45.0, timestamp: '00:45', sharpness: 168 },
      { path: '/evidence/frames/bedroom_parents/01_t043.0.jpg', seconds: 43.0, timestamp: '00:43', sharpness: 5710 },
      { path: '/evidence/frames/bedroom_parents/02_t043.8.jpg', seconds: 43.8, timestamp: '00:43', sharpness: 3397 },
      { path: '/evidence/frames/bedroom_parents/03_t044.5.jpg', seconds: 44.5, timestamp: '00:44', sharpness: 5126 },
      { path: '/evidence/frames/bedroom_parents/04_t045.9.jpg', seconds: 45.9, timestamp: '00:45', sharpness: 691 },
    ],
  },
};

/** First shot of each room's gallery - the single representative still. */
export const roomEvidenceFrame: Record<RoomId, EvidenceShot> =
  Object.fromEntries(
    Object.entries(roomEvidence).map(([id, e]) => [id, e.shots[0]]),
  ) as Record<RoomId, EvidenceShot>;
